# Site settings
title: Journey of Growth
header-img: img/home-bg.png
email: freddymorato@gmail.com
copyright_name: Freddymorato
description: > # this means to ignore newlines until "baseurl:"
  The blog of an aspiring software developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Freddymorato
learn_profile: Freddymorato
email_username: freddymorato@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
